Repository appknox/website, pull requests merged in 2018-09, with the labels that each got.

#240 Remove pricing label
  _data/pricingplans.yml
  _i18n/en/index/pricing.html
  _i18n/in/index/pricing.html
  _i18n/jp/index/pricing.html
Labels: review

#241 Use Netlify config instead of custom files
  _config.yml
  _redirects
  netlify.toml
Labels: in progress

#242 Update dependencies
  Gemfile.lock
Labels: in progress

#243 Adding 3 more slides to global website
  _i18n/en/index/slider.html
  _includes/security-status-section.html
  img/slides/top-slides/slider-7.png
  img/slides/top-slides/slider-8.png
  img/slides/top-slides/slider-9.png
Labels: in progress, review
